// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZFAOF2lEXONTwvi1iNaMZvJiPETzlpE',
    appId: '1:673672806430:web:06a8f37bdc36c5a602ae0f',
    messagingSenderId: '673672806430',
    projectId: 'iot15-46c28',
    authDomain: 'iot15-46c28.firebaseapp.com',
    databaseURL: 'https://iot15-46c28-default-rtdb.firebaseio.com',
    storageBucket: 'iot15-46c28.firebasestorage.app',
    measurementId: 'G-0FM03BQEB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzEs0U397nzZuKDzf79l6Qu3TFJ8sByM',
    appId: '1:673672806430:android:f71476b191cc46ae02ae0f',
    messagingSenderId: '673672806430',
    projectId: 'iot15-46c28',
    databaseURL: 'https://iot15-46c28-default-rtdb.firebaseio.com',
    storageBucket: 'iot15-46c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKlcP6DAtXAehmXxDyldzkNYbN8lvi67A',
    appId: '1:673672806430:ios:7ccaf93fc2ae82e902ae0f',
    messagingSenderId: '673672806430',
    projectId: 'iot15-46c28',
    databaseURL: 'https://iot15-46c28-default-rtdb.firebaseio.com',
    storageBucket: 'iot15-46c28.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKlcP6DAtXAehmXxDyldzkNYbN8lvi67A',
    appId: '1:673672806430:ios:7ccaf93fc2ae82e902ae0f',
    messagingSenderId: '673672806430',
    projectId: 'iot15-46c28',
    databaseURL: 'https://iot15-46c28-default-rtdb.firebaseio.com',
    storageBucket: 'iot15-46c28.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZZFAOF2lEXONTwvi1iNaMZvJiPETzlpE',
    appId: '1:673672806430:web:cd6ce16e7c86768902ae0f',
    messagingSenderId: '673672806430',
    projectId: 'iot15-46c28',
    authDomain: 'iot15-46c28.firebaseapp.com',
    databaseURL: 'https://iot15-46c28-default-rtdb.firebaseio.com',
    storageBucket: 'iot15-46c28.firebasestorage.app',
    measurementId: 'G-WRRVJZHN92',
  );
}
